name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/jutsteex/pythonapp:1.0 .
      - run: docker push ghcr.io/jutsteex/pythonapp:1.0
      - run: docker build -t ghcr.io/jutsteex/nodeapp:1.0 .
      - run: docker push ghcr.io/jutsteex/nodeapp:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'jutsteex-dolgdecabr1-oktw8ei3b9q#vEw940S3PI2EsOhhSO6fNHGIFFATIJqx@jutsteex-dolgdecabr1-oktw8ei3b9q.ssh.ws-eu110.gitpod.io' "cd /workspace/dolgdecabr1 && docker compose pull && docker compose up -d"
      - name: send default message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано успешно"
          to: 694432088
          token: 7138679289:AAG-etn0gFzzwwUFOe0S3rOLBKW-APpow5U
      - name: send default message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано no успешно"
          to: 694432088
          token: 7138679289:AAG-etn0gFzzwwUFOe0S3rOLBKW-APpow5U
